apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name.dcn }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name.dcn }}
  template:
    metadata:
      labels:
        app: {{ .Values.name.dcn }}
    spec:
      containers:
        - name: {{ .Values.name.dcn }}
          image: "ghcr.io/oliver-zehentleitner/ubdcc-dcn:{{ .Chart.AppVersion }}"
