files:
- .github/workflows/build_wheels_ubdcc.yml
- .github/workflows/build_wheels_ubdcc_dcn.yml
- .github/workflows/build_wheels_ubdcc_mgmt.yml
- .github/workflows/build_wheels_ubdcc_restapi.yml
- .github/workflows/build_wheels_ubdcc_shared_modules.yml
- .github/workflows/docker_build.yml
- admin/k8s/ubdcc-dcn.yaml
- admin/k8s/ubdcc-mgmt.yaml
- admin/k8s/ubdcc-restapi.yaml
- .github/workflows/gh_release.yml
- container/generic_loader/requirements-ubdcc_dcn.txt
- container/generic_loader/requirements-ubdcc_mgmt.txt
- container/generic_loader/requirements-ubdcc_restapi.txt
- dev/helm/ubdcc/Chart.yaml
- dev/sphinx/source/conf.py
- packages/ubdcc/pyproject.toml
- packages/ubdcc/requirements.txt
- packages/ubdcc/setup.py
- packages/ubdcc-dcn/pyproject.toml
- packages/ubdcc-dcn/requirements.txt
- packages/ubdcc-dcn/setup.py
- packages/ubdcc-mgmt/pyproject.toml
- packages/ubdcc-mgmt/requirements.txt
- packages/ubdcc-mgmt/setup.py
- packages/ubdcc-restapi/pyproject.toml
- packages/ubdcc-restapi/requirements.txt
- packages/ubdcc-restapi/setup.py
- packages/ubdcc-shared-modules/ubdcc_shared_modules/App.py
- packages/ubdcc-shared-modules/pyproject.toml
- packages/ubdcc-shared-modules/setup.py
- README.md
- AGENTS.md
version: 0.4.0.dev
