blank_issues_enabled: true
contact_links:
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat with the community about the UNICORN Binance DepthCache Cluster and ask general questions.
  - name: UNICORN Binance DepthCache Cluster Discussions
    url: https://github.com/oliver-zehentleitner/unicorn-depthcache-cluster-for-binance/discussions
    about: Ask general questions.
  - name: UNICORN Binance DepthCache Cluster documentation
    url: https://oliver-zehentleitner.github.io/unicorn-depthcache-cluster-for-binance/
    about: The complete UNICORN Binance DepthCache Cluster documentation.
  - name: Get Professional and Fast Support
    url: https://about.me/oliver-zehentleitner/get-support.html
    about: Contact the LUCIT Development Team.
  - name: Get a UNICORN Trading Suite License
    url: https://github.com/oliver-zehentleitner/unicorn-trading-suite
    about: LUCIT Online Shop