apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mgmt-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ubdcc-mgmt
subjects:
- kind: ServiceAccount
  name: default
  namespace: ubdcc
