FROM python:3.12.3-slim

WORKDIR /app/generic_loader

RUN mkdir -vp /app/generic_loader

COPY ./container/generic_loader/ /app/generic_loader

RUN python -m venv /app/venv

CMD ["/bin/sh", "-c", "python -m venv /app/venv && \
    . /app/venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements-ubdcc_mgmt.txt && \
    python start_ubdcc_mgmt.py"]