name: Build and Publish PyPi (ubdcc)

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific directory
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: checkout
          sparse-checkout: 'packages/ubdcc/'

      - name: Move directory contents
        run: |
          mv checkout/packages/ubdcc/* ./
          rm -rf checkout

      - name: ls -l
        run: ls -l

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist/*

  Release:
    needs: [build]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Create PyPi Release
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
