apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubdcc-dcn
  namespace: ubdcc
spec:
  selector:
    matchLabels:
      app: ubdcc-dcn
  template:
    metadata:
      labels:
        app: ubdcc-dcn
    spec:
      containers:
        - name: ubdcc-dcn
          image: ghcr.io/oliver-zehentleitner/ubdcc-dcn:0.4.0.dev
